apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-agv
  labels:
    app: java
  namespace: agv-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: docker.io/library/javaaa-agv:VERSION_TAG_PLACEHOLDER
          imagePullPolicy: Never
          ports:
            - containerPort: 8080